# healthcheck.ps1 checks IIS service, website availability, CPU, memory, and disk usage, then outputs the results in JSON format so Ansible can read it.
---
- name: Upload and run Windows health check script
  hosts: windows
  gather_facts: no

  vars:
    script_path: "C:\\Scripts\\healthcheck.ps1"

  tasks:

    - name: Ensure Scripts folder exists
      ansible.windows.win_file:
        path: "C:\\Scripts"
        state: directory

    - name: Upload script
      ansible.windows.win_copy:
        src: "./scripts/healthcheck.ps1"
        dest: "{{ script_path }}"

    - name: Run healthcheck script using win_command
      ansible.windows.win_command: |
        powershell.exe -ExecutionPolicy Bypass -File "{{ script_path }}"
      register: health_output

    - name: Show health check output
      ansible.builtin.debug:
        var: health_output.stdout
